//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieArchive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieArchive.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MovieArchive.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonConfirmCancelRestore {
            get {
                return ResourceManager.GetString("ButtonConfirmCancelRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonConfirmResetDBCancel {
            get {
                return ResourceManager.GetString("ButtonConfirmResetDBCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ButtonConfirmResetDBReset {
            get {
                return ResourceManager.GetString("ButtonConfirmResetDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string ButtonConfirmRestore {
            get {
                return ResourceManager.GetString("ButtonConfirmRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ButtonImportFromFile {
            get {
                return ResourceManager.GetString("ButtonImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string ButtonImportFromFolder {
            get {
                return ResourceManager.GetString("ButtonImportFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebApi.
        /// </summary>
        internal static string ButtonImportFromWebApi {
            get {
                return ResourceManager.GetString("ButtonImportFromWebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New movie.
        /// </summary>
        internal static string ButtonImportVariation {
            get {
                return ResourceManager.GetString("ButtonImportVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset DB.
        /// </summary>
        internal static string ButtonResetDB {
            get {
                return ResourceManager.GetString("ButtonResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string ButtonRestoreDB {
            get {
                return ResourceManager.GetString("ButtonRestoreDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during save file.
        /// </summary>
        internal static string ErrorMessageCvsFileExported {
            get {
                return ResourceManager.GetString("ErrorMessageCvsFileExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic backup.
        /// </summary>
        internal static string LabelAutomaticBackup {
            get {
                return ResourceManager.GetString("LabelAutomaticBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete reset of local DB.
        /// </summary>
        internal static string LabelCompleteDBReset {
            get {
                return ResourceManager.GetString("LabelCompleteDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File search.
        /// </summary>
        internal static string LabelImportFromFolder {
            get {
                return ResourceManager.GetString("LabelImportFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie DB reset.
        /// </summary>
        internal static string LabelMovieDBReset {
            get {
                return ResourceManager.GetString("LabelMovieDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movie found.
        /// </summary>
        internal static string LabelNoMovieFound {
            get {
                return ResourceManager.GetString("LabelNoMovieFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore DB from DropBox.
        /// </summary>
        internal static string LabelRestoreDB {
            get {
                return ResourceManager.GetString("LabelRestoreDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        internal static string LabelTitleActors {
            get {
                return ResourceManager.GetString("LabelTitleActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string LabelTitleDirector {
            get {
                return ResourceManager.GetString("LabelTitleDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string LabelTitleGenres {
            get {
                return ResourceManager.GetString("LabelTitleGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original title.
        /// </summary>
        internal static string LabelTitleOriginalTitle {
            get {
                return ResourceManager.GetString("LabelTitleOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string LabelTitlePersonBirthday {
            get {
                return ResourceManager.GetString("LabelTitlePersonBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathday.
        /// </summary>
        internal static string LabelTitlePersonDeathday {
            get {
                return ResourceManager.GetString("LabelTitlePersonDeathday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string LabelTitlePersonGender {
            get {
                return ResourceManager.GetString("LabelTitlePersonGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string LabelTitlePersonHomepage {
            get {
                return ResourceManager.GetString("LabelTitlePersonHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birthday.
        /// </summary>
        internal static string LabelTitlePersonPlaceOfBirth {
            get {
                return ResourceManager.GetString("LabelTitlePersonPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string LabelTitleProductionCountry {
            get {
                return ResourceManager.GetString("LabelTitleProductionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal rating.
        /// </summary>
        internal static string LabelTitleRating {
            get {
                return ResourceManager.GetString("LabelTitleRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web rating.
        /// </summary>
        internal static string LabelTitleRatingList {
            get {
                return ResourceManager.GetString("LabelTitleRatingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year.
        /// </summary>
        internal static string LabelTitleReleaseDate {
            get {
                return ResourceManager.GetString("LabelTitleReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        internal static string LabelTitleRuntime {
            get {
                return ResourceManager.GetString("LabelTitleRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tv show DB reset.
        /// </summary>
        internal static string LabelTvShowDBReset {
            get {
                return ResourceManager.GetString("LabelTvShowDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to MovieArchive.
        /// </summary>
        internal static string LabelWelcomeMessage1 {
            get {
                return ResourceManager.GetString("LabelWelcomeMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start go to Add.
        /// </summary>
        internal static string LabelWelcomeMessage2 {
            get {
                return ResourceManager.GetString("LabelWelcomeMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service address.
        /// </summary>
        internal static string LabelWSAddress {
            get {
                return ResourceManager.GetString("LabelWSAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuTitlePage1 {
            get {
                return ResourceManager.GetString("MenuTitlePage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string MenuTitlePage2 {
            get {
                return ResourceManager.GetString("MenuTitlePage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tv Show.
        /// </summary>
        internal static string MenuTitlePage3 {
            get {
                return ResourceManager.GetString("MenuTitlePage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MenuTitlePage4 {
            get {
                return ResourceManager.GetString("MenuTitlePage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string MenuTitlePage5 {
            get {
                return ResourceManager.GetString("MenuTitlePage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to add.
        /// </summary>
        internal static string Message0MovieImported {
            get {
                return ResourceManager.GetString("Message0MovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Reset DB?.
        /// </summary>
        internal static string MessageConfirmResetDB {
            get {
                return ResourceManager.GetString("MessageConfirmResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore database backup?.
        /// </summary>
        internal static string MessageConfirmRestoreDB {
            get {
                return ResourceManager.GetString("MessageConfirmRestoreDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved.
        /// </summary>
        internal static string MessageCvsFileExported {
            get {
                return ResourceManager.GetString("MessageCvsFileExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database restored.
        /// </summary>
        internal static string MessageDataBaseRestored {
            get {
                return ResourceManager.GetString("MessageDataBaseRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropBox connected.
        /// </summary>
        internal static string MessageDropBoxConnected {
            get {
                return ResourceManager.GetString("MessageDropBoxConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropBox not connected.
        /// </summary>
        internal static string MessageDropBoxNotConnected {
            get {
                return ResourceManager.GetString("MessageDropBoxNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB initialized.
        /// </summary>
        internal static string MessageMovieDBReset {
            get {
                return ResourceManager.GetString("MessageMovieDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added movie.
        /// </summary>
        internal static string MessageNMovieImported {
            get {
                return ResourceManager.GetString("MessageNMovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating saved.
        /// </summary>
        internal static string MessageRatingSaved {
            get {
                return ResourceManager.GetString("MessageRatingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Added.
        /// </summary>
        internal static string MessageTitleMovieImported {
            get {
                return ResourceManager.GetString("MessageTitleMovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Added.
        /// </summary>
        internal static string MessageTitleTvShowImported {
            get {
                return ResourceManager.GetString("MessageTitleTvShowImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB initialized.
        /// </summary>
        internal static string MessageTotalDBReset {
            get {
                return ResourceManager.GetString("MessageTotalDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebApi address error.
        /// </summary>
        internal static string MessageWebApiNotActive {
            get {
                return ResourceManager.GetString("MessageWebApiNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        internal static string SearchBarPlaceHoler {
            get {
                return ResourceManager.GetString("SearchBarPlaceHoler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB reset.
        /// </summary>
        internal static string TitleConfirmResetDB {
            get {
                return ResourceManager.GetString("TitleConfirmResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB restore.
        /// </summary>
        internal static string TitleConfirmRestoreDB {
            get {
                return ResourceManager.GetString("TitleConfirmRestoreDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best rating movie.
        /// </summary>
        internal static string TitleDashBoardBest3RatedMovie {
            get {
                return ResourceManager.GetString("TitleDashBoardBest3RatedMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last movie add.
        /// </summary>
        internal static string TitleDashBoardLast3MovieAdd {
            get {
                return ResourceManager.GetString("TitleDashBoardLast3MovieAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last movie seen.
        /// </summary>
        internal static string TitleDashBoardLast3MovieSeen {
            get {
                return ResourceManager.GetString("TitleDashBoardLast3MovieSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 tv shows seen.
        /// </summary>
        internal static string TitleDashBoardLast3TvShowEpisodeSeen {
            get {
                return ResourceManager.GetString("TitleDashBoardLast3TvShowEpisodeSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TitlePageDashBoard {
            get {
                return ResourceManager.GetString("TitlePageDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string TitlePageInsertMedia {
            get {
                return ResourceManager.GetString("TitlePageInsertMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string TitlePageMovieCard {
            get {
                return ResourceManager.GetString("TitlePageMovieCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string TitlePageMovieList {
            get {
                return ResourceManager.GetString("TitlePageMovieList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TitlePageProperty {
            get {
                return ResourceManager.GetString("TitlePageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string TitlePageSearchResult {
            get {
                return ResourceManager.GetString("TitlePageSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tv Show.
        /// </summary>
        internal static string TitlePageTvShowList {
            get {
                return ResourceManager.GetString("TitlePageTvShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season .
        /// </summary>
        internal static string TitleSeasonDetails {
            get {
                return ResourceManager.GetString("TitleSeasonDetails", resourceCulture);
            }
        }
    }
}
