//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieArchive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieArchive.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MovieArchive.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ButtonImportFromFile {
            get {
                return ResourceManager.GetString("ButtonImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string ButtonImportFromFolder {
            get {
                return ResourceManager.GetString("ButtonImportFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebApi.
        /// </summary>
        internal static string ButtonImportFromWebApi {
            get {
                return ResourceManager.GetString("ButtonImportFromWebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variazioni.
        /// </summary>
        internal static string ButtonImportVariation {
            get {
                return ResourceManager.GetString("ButtonImportVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset DB.
        /// </summary>
        internal static string ButtonResetDB {
            get {
                return ResourceManager.GetString("ButtonResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup automartico.
        /// </summary>
        internal static string LabelAutomaticBackup {
            get {
                return ResourceManager.GetString("LabelAutomaticBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset completo del DB locale.
        /// </summary>
        internal static string LabelCompleteDBReset {
            get {
                return ResourceManager.GetString("LabelCompleteDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca file da importare.
        /// </summary>
        internal static string LabelImportFromFolder {
            get {
                return ResourceManager.GetString("LabelImportFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset del DB film locale.
        /// </summary>
        internal static string LabelMovieDBReset {
            get {
                return ResourceManager.GetString("LabelMovieDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attori.
        /// </summary>
        internal static string LabelTitleActors {
            get {
                return ResourceManager.GetString("LabelTitleActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voto medio.
        /// </summary>
        internal static string LabelTitleAVGRating {
            get {
                return ResourceManager.GetString("LabelTitleAVGRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regista.
        /// </summary>
        internal static string LabelTitleDirector {
            get {
                return ResourceManager.GetString("LabelTitleDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titolo originale.
        /// </summary>
        internal static string LabelTitleOriginalTitle {
            get {
                return ResourceManager.GetString("LabelTitleOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paese.
        /// </summary>
        internal static string LabelTitleProductionCountry {
            get {
                return ResourceManager.GetString("LabelTitleProductionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anno di produzione.
        /// </summary>
        internal static string LabelTitleReleaseDate {
            get {
                return ResourceManager.GetString("LabelTitleReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata.
        /// </summary>
        internal static string LabelTitleRuntime {
            get {
                return ResourceManager.GetString("LabelTitleRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo web service.
        /// </summary>
        internal static string LabelWSAddress {
            get {
                return ResourceManager.GetString("LabelWSAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuTitlePage1 {
            get {
                return ResourceManager.GetString("MenuTitlePage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da vedere.
        /// </summary>
        internal static string MenuTitlePage2 {
            get {
                return ResourceManager.GetString("MenuTitlePage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visti.
        /// </summary>
        internal static string MenuTitlePage3 {
            get {
                return ResourceManager.GetString("MenuTitlePage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi film.
        /// </summary>
        internal static string MenuTitlePage4 {
            get {
                return ResourceManager.GetString("MenuTitlePage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proprietà.
        /// </summary>
        internal static string MenuTitlePage5 {
            get {
                return ResourceManager.GetString("MenuTitlePage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun film aggiunto.
        /// </summary>
        internal static string Message0MovieImported {
            get {
                return ResourceManager.GetString("Message0MovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db dei film resettato.
        /// </summary>
        internal static string MessageMovieDBReset {
            get {
                return ResourceManager.GetString("MessageMovieDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} film aggiunti.
        /// </summary>
        internal static string MessageNMovieImported {
            get {
                return ResourceManager.GetString("MessageNMovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voto registrato.
        /// </summary>
        internal static string MessageRatingSaved {
            get {
                return ResourceManager.GetString("MessageRatingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Aggiunto.
        /// </summary>
        internal static string MessageTitleMovieImported {
            get {
                return ResourceManager.GetString("MessageTitleMovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db completamente resettato.
        /// </summary>
        internal static string MessageTotalDBReset {
            get {
                return ResourceManager.GetString("MessageTotalDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca....
        /// </summary>
        internal static string SearchBarPlaceHoler {
            get {
                return ResourceManager.GetString("SearchBarPlaceHoler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miglior film votati.
        /// </summary>
        internal static string TitleDashBoardBest3RatedMovie {
            get {
                return ResourceManager.GetString("TitleDashBoardBest3RatedMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimi film aggiunti.
        /// </summary>
        internal static string TitleDashBoardLast3MovieAdd {
            get {
                return ResourceManager.GetString("TitleDashBoardLast3MovieAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimi film visti.
        /// </summary>
        internal static string TitleDashBoardLast3MovieSeen {
            get {
                return ResourceManager.GetString("TitleDashBoardLast3MovieSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string TitlePageDashBoard {
            get {
                return ResourceManager.GetString("TitlePageDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi film.
        /// </summary>
        internal static string TitlePageInsertMovue {
            get {
                return ResourceManager.GetString("TitlePageInsertMovue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        internal static string TitlePageMovieCard {
            get {
                return ResourceManager.GetString("TitlePageMovieCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film visti.
        /// </summary>
        internal static string TitlePageMovieSeen {
            get {
                return ResourceManager.GetString("TitlePageMovieSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film da vedere.
        /// </summary>
        internal static string TitlePageMovieUnseen {
            get {
                return ResourceManager.GetString("TitlePageMovieUnseen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proprietà.
        /// </summary>
        internal static string TitlePageProperty {
            get {
                return ResourceManager.GetString("TitlePageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risultati.
        /// </summary>
        internal static string TitlePageSearchResult {
            get {
                return ResourceManager.GetString("TitlePageSearchResult", resourceCulture);
            }
        }
    }
}
