//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieArchive.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieArchive.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MovieArchive.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string ButtonConfirmCancelRestore {
            get {
                return ResourceManager.GetString("ButtonConfirmCancelRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string ButtonConfirmResetDBCancel {
            get {
                return ResourceManager.GetString("ButtonConfirmResetDBCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset.
        /// </summary>
        internal static string ButtonConfirmResetDBReset {
            get {
                return ResourceManager.GetString("ButtonConfirmResetDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restore.
        /// </summary>
        internal static string ButtonConfirmRestore {
            get {
                return ResourceManager.GetString("ButtonConfirmRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        internal static string ButtonImportFromFile {
            get {
                return ResourceManager.GetString("ButtonImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory.
        /// </summary>
        internal static string ButtonImportFromFolder {
            get {
                return ResourceManager.GetString("ButtonImportFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a WebApi.
        /// </summary>
        internal static string ButtonImportFromWebApi {
            get {
                return ResourceManager.GetString("ButtonImportFromWebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New movie.
        /// </summary>
        internal static string ButtonImportVariation {
            get {
                return ResourceManager.GetString("ButtonImportVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset DB.
        /// </summary>
        internal static string ButtonResetDB {
            get {
                return ResourceManager.GetString("ButtonResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restore.
        /// </summary>
        internal static string ButtonRestoreDB {
            get {
                return ResourceManager.GetString("ButtonRestoreDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during save file.
        /// </summary>
        internal static string ErrorMessageCvsFileExported {
            get {
                return ResourceManager.GetString("ErrorMessageCvsFileExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Automatic backup.
        /// </summary>
        internal static string LabelAutomaticBackup {
            get {
                return ResourceManager.GetString("LabelAutomaticBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Complete reset of local DB.
        /// </summary>
        internal static string LabelCompleteDBReset {
            get {
                return ResourceManager.GetString("LabelCompleteDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File search.
        /// </summary>
        internal static string LabelImportFromFolder {
            get {
                return ResourceManager.GetString("LabelImportFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Movie DB reset.
        /// </summary>
        internal static string LabelMovieDBReset {
            get {
                return ResourceManager.GetString("LabelMovieDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No movie found.
        /// </summary>
        internal static string LabelNoMovieFound {
            get {
                return ResourceManager.GetString("LabelNoMovieFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restore DB from DropBox.
        /// </summary>
        internal static string LabelRestoreDB {
            get {
                return ResourceManager.GetString("LabelRestoreDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Actors.
        /// </summary>
        internal static string LabelTitleActors {
            get {
                return ResourceManager.GetString("LabelTitleActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Director.
        /// </summary>
        internal static string LabelTitleDirector {
            get {
                return ResourceManager.GetString("LabelTitleDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genres.
        /// </summary>
        internal static string LabelTitleGenres {
            get {
                return ResourceManager.GetString("LabelTitleGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Original title.
        /// </summary>
        internal static string LabelTitleOriginalTitle {
            get {
                return ResourceManager.GetString("LabelTitleOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Birthday.
        /// </summary>
        internal static string LabelTitlePersonBirthday {
            get {
                return ResourceManager.GetString("LabelTitlePersonBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deathday.
        /// </summary>
        internal static string LabelTitlePersonDeathday {
            get {
                return ResourceManager.GetString("LabelTitlePersonDeathday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gender.
        /// </summary>
        internal static string LabelTitlePersonGender {
            get {
                return ResourceManager.GetString("LabelTitlePersonGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Home page.
        /// </summary>
        internal static string LabelTitlePersonHomepage {
            get {
                return ResourceManager.GetString("LabelTitlePersonHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Place of birthday.
        /// </summary>
        internal static string LabelTitlePersonPlaceOfBirth {
            get {
                return ResourceManager.GetString("LabelTitlePersonPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Country.
        /// </summary>
        internal static string LabelTitleProductionCountry {
            get {
                return ResourceManager.GetString("LabelTitleProductionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Personal rating.
        /// </summary>
        internal static string LabelTitleRating {
            get {
                return ResourceManager.GetString("LabelTitleRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web rating.
        /// </summary>
        internal static string LabelTitleRatingList {
            get {
                return ResourceManager.GetString("LabelTitleRatingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Release year.
        /// </summary>
        internal static string LabelTitleReleaseDate {
            get {
                return ResourceManager.GetString("LabelTitleReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Runtime.
        /// </summary>
        internal static string LabelTitleRuntime {
            get {
                return ResourceManager.GetString("LabelTitleRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tv show DB reset.
        /// </summary>
        internal static string LabelTvShowDBReset {
            get {
                return ResourceManager.GetString("LabelTvShowDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome to MovieArchive.
        /// </summary>
        internal static string LabelWelcomeMessage1 {
            get {
                return ResourceManager.GetString("LabelWelcomeMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To start go to Add.
        /// </summary>
        internal static string LabelWelcomeMessage2 {
            get {
                return ResourceManager.GetString("LabelWelcomeMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web service address.
        /// </summary>
        internal static string LabelWSAddress {
            get {
                return ResourceManager.GetString("LabelWSAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Home.
        /// </summary>
        internal static string MenuTitlePage1 {
            get {
                return ResourceManager.GetString("MenuTitlePage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Movie.
        /// </summary>
        internal static string MenuTitlePage2 {
            get {
                return ResourceManager.GetString("MenuTitlePage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tv Show.
        /// </summary>
        internal static string MenuTitlePage3 {
            get {
                return ResourceManager.GetString("MenuTitlePage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add.
        /// </summary>
        internal static string MenuTitlePage4 {
            get {
                return ResourceManager.GetString("MenuTitlePage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Properties.
        /// </summary>
        internal static string MenuTitlePage5 {
            get {
                return ResourceManager.GetString("MenuTitlePage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nothing to add.
        /// </summary>
        internal static string Message0MovieImported {
            get {
                return ResourceManager.GetString("Message0MovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm Reset DB?.
        /// </summary>
        internal static string MessageConfirmResetDB {
            get {
                return ResourceManager.GetString("MessageConfirmResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restore database backup?.
        /// </summary>
        internal static string MessageConfirmRestoreDB {
            get {
                return ResourceManager.GetString("MessageConfirmRestoreDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File saved.
        /// </summary>
        internal static string MessageCvsFileExported {
            get {
                return ResourceManager.GetString("MessageCvsFileExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Database restored.
        /// </summary>
        internal static string MessageDataBaseRestored {
            get {
                return ResourceManager.GetString("MessageDataBaseRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DropBox connected.
        /// </summary>
        internal static string MessageDropBoxConnected {
            get {
                return ResourceManager.GetString("MessageDropBoxConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DropBox not connected.
        /// </summary>
        internal static string MessageDropBoxNotConnected {
            get {
                return ResourceManager.GetString("MessageDropBoxNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB initialized.
        /// </summary>
        internal static string MessageMovieDBReset {
            get {
                return ResourceManager.GetString("MessageMovieDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} added movie.
        /// </summary>
        internal static string MessageNMovieImported {
            get {
                return ResourceManager.GetString("MessageNMovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rating saved.
        /// </summary>
        internal static string MessageRatingSaved {
            get {
                return ResourceManager.GetString("MessageRatingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} Added.
        /// </summary>
        internal static string MessageTitleMovieImported {
            get {
                return ResourceManager.GetString("MessageTitleMovieImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} Added.
        /// </summary>
        internal static string MessageTitleTvShowImported {
            get {
                return ResourceManager.GetString("MessageTitleTvShowImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB initialized.
        /// </summary>
        internal static string MessageTotalDBReset {
            get {
                return ResourceManager.GetString("MessageTotalDBReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a WebApi address error.
        /// </summary>
        internal static string MessageWebApiNotActive {
            get {
                return ResourceManager.GetString("MessageWebApiNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find....
        /// </summary>
        internal static string SearchBarPlaceHoler {
            get {
                return ResourceManager.GetString("SearchBarPlaceHoler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB reset.
        /// </summary>
        internal static string TitleConfirmResetDB {
            get {
                return ResourceManager.GetString("TitleConfirmResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB restore.
        /// </summary>
        internal static string TitleConfirmRestoreDB {
            get {
                return ResourceManager.GetString("TitleConfirmRestoreDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Best rating movie.
        /// </summary>
        internal static string TitleDashBoardBest3RatedMovie {
            get {
                return ResourceManager.GetString("TitleDashBoardBest3RatedMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last movie add.
        /// </summary>
        internal static string TitleDashBoardLast3MovieAdd {
            get {
                return ResourceManager.GetString("TitleDashBoardLast3MovieAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last movie seen.
        /// </summary>
        internal static string TitleDashBoardLast3MovieSeen {
            get {
                return ResourceManager.GetString("TitleDashBoardLast3MovieSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last 3 tv shows seen.
        /// </summary>
        internal static string TitleDashBoardLast3TvShowEpisodeSeen {
            get {
                return ResourceManager.GetString("TitleDashBoardLast3TvShowEpisodeSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Home.
        /// </summary>
        internal static string TitlePageDashBoard {
            get {
                return ResourceManager.GetString("TitlePageDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add.
        /// </summary>
        internal static string TitlePageInsertMedia {
            get {
                return ResourceManager.GetString("TitlePageInsertMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Movie.
        /// </summary>
        internal static string TitlePageMovieCard {
            get {
                return ResourceManager.GetString("TitlePageMovieCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Movie.
        /// </summary>
        internal static string TitlePageMovieList {
            get {
                return ResourceManager.GetString("TitlePageMovieList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        internal static string TitlePageProperty {
            get {
                return ResourceManager.GetString("TitlePageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Result.
        /// </summary>
        internal static string TitlePageSearchResult {
            get {
                return ResourceManager.GetString("TitlePageSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tv Show.
        /// </summary>
        internal static string TitlePageTvShowList {
            get {
                return ResourceManager.GetString("TitlePageTvShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Season .
        /// </summary>
        internal static string TitleSeasonDetails {
            get {
                return ResourceManager.GetString("TitleSeasonDetails", resourceCulture);
            }
        }
    }
}
